[discord]
    [discord.mydiscord]
    Token="NzI3MjY4OTc2MzAzOTMxNTQ0.XvpYAw.uNNOQCEg0Hj5uk54WoGoAqfbiiw"
    Server="gbdev"
    RemoteNickFormat="{NICK}: "

    [discord.gbadiscord]
    Token="NzI3MjY4OTc2MzAzOTMxNTQ0.XvpYAw.uNNOQCEg0Hj5uk54WoGoAqfbiiw"
    Server="gbadev"
    RemoteNickFormat="{NICK}: "

[irc.myirc]
Server="irc.efnet.org:6667"
Nick="gb-bridge"
RemoteNickFormat="<{NICK}> "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="general"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2"

[[gateway]]
name="gbagateway"
enable=true

[[gateway.inout]]
account="discord.gbadiscord"
channel="general"

[[gateway.inout]]
account="irc.myirc"
channel="#gbadev"

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="off-topic"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-off-topic"

[[gateway]]
name="gateway3"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="emudev"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-emudev"

[[gateway]]
name="gateway4"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="gbdk"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-gbdk"

[[gateway]]
name="gateway5"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="research"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-research"

[[gateway]]
name="gateway6"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="hardware"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-hardware"

[[gateway]]
name="gateway7"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="tools"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-tools"

[[gateway]]
name="gateway8"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="showcase"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-showcase"

[[gateway]]
name="gateway9"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="music"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-music"

[[gateway]]
name="gateway11"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="meta"

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev2-meta"
