# Matterbridge configuration for the gb and gbadev communities
# bridges Discord channels to IRC
# https://gbdev.io

# Discord servers
[discord]
    [discord.gbdev]
    Token="<DISCORD_BOT_TOKEN>"
    Server="gbdev"
    RemoteNickFormat="{NICK}: "

    [discord.gbadev]
    Token="<DISCORD_BOT_TOKEN>"
    Server="gbadev"
    RemoteNickFormat="{NICK}: "

# IRC (EFNet)
[irc.efnet]
Server="irc.efnet.fr:6667"
Nick="gb-bridge"
RemoteNickFormat="<{NICK}> "


# Bridge gateways

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="general"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2"

[[gateway]]
name="gbagateway"
enable=true

[[gateway.inout]]
account="discord.gbadev"
channel="general"

[[gateway.inout]]
account="irc.efnet"
channel="#gbadev"

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="off-topic"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-off-topic"

[[gateway]]
name="gateway3"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="emudev"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-emudev"

[[gateway]]
name="gateway4"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="gbdk"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-gbdk"

[[gateway]]
name="gateway5"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="research"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-research"

[[gateway]]
name="gateway6"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="hardware"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-hardware"

[[gateway]]
name="gateway7"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="tools"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-tools"

[[gateway]]
name="gateway8"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="showcase"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-showcase"

[[gateway]]
name="gateway9"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="music"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-music"

[[gateway]]
name="gateway11"
enable=true

[[gateway.inout]]
account="discord.gbdev"
channel="meta"

[[gateway.inout]]
account="irc.efnet"
channel="#gbdev2-meta"
